### PR TITLE
Complete initial implementation

### PR DESCRIPTION
**Pull request by iyear**
Please see: https://github.com/iyear/ospp-go-grpc

1. Testings
2. Examples: `convert` & `devstream`
3. Simple docs
4. Necessary comments

PTAL @IronCore864

### CODE REVIEW

**Comment by iyear** [comment]
Please review, I will start trying to research migration.

**Comment by iyear** [comment]
Please review, I will start trying to research migration. @IronCore864

**Comment by iyear** [comment]
Please review, I will start trying to research migration. @IronCore864

**Comment by iyear** [comment]
Please review. @IronCore864 @daniel-hutao

**Review by IronCore864 — APPROVED** [review]

**Pull request merged**
